 const BiharEngineeringBranches = [
  "Computer Science and Engineering (CSE)",
  "Electronics and Communication Engineering (ECE)",
  "Electrical Engineering (EE)",
  "Electrical and Electronics Engineering (EEE)",
  "Mechanical Engineering (ME)",
  "Civil Engineering (CE)",
  "Information Technology (IT)",
  "Artificial Intelligence (AI)",
  "Artificial Intelligence & Machine Learning (AI & ML)",
  "Data Science",
  "Computer Science & Engineering with Cyber Security",
  "Computer Science & Engineering with IoT",
  "Electronics and Instrumentation Engineering",
  "Instrumentation and Control Engineering",
  "Automation and Robotics",
  "Biomedical Engineering",
  "Mechatronics Engineering",
  "Aerospace Engineering",
  "Aeronautical Engineering",
  "Environmental Engineering",
  "Food Processing & Preservation Engineering",
  "Civil Engineering with Computer Application",
  "Agricultural Engineering",
  "Mining Engineering",
  "Textile Engineering",
  "Chemical Engineering",
  "Metallurgical Engineering",
  "Petroleum Engineering",
  "Marine Engineering",
  "Fire Technology"
];

export default BiharEngineeringBranches