  const governmentEngineeringColleges = [
  "Muzaffarpur Institute of Technology (MIT), Muzaffarpur",
  "Bihar College of Engineering (BCE), Bhagalpur",
  "Gaya College of Engineering (GCE), Gaya",
  "Darbhanga College of Engineering (DCE), Darbhanga",
  "Motihari College of Engineering (MCE), Motihari",
  "Nalanda College of Engineering (NCE), Chandi",
  "Loknayak Jai Prakash Institute of Technology (LJTI), Chhapra",
  "Sitamarhi Institute of Technology (SIT), Sitamarhi",
  "Buddha Polytechnic & Engineering College (BPMEC), Madhepura",
  "Ramdhari Singh Dinkar College of Engineering (RRSDCE), Begusarai",
  "Shershah Engineering College (SEC), Sasaram",
  "Katihar Engineering College (KEC), Katihar",
  "Bakhtiyarpur Engineering College (BEC), Bakhtiyarpur",
  "Saharsa Engineering College (SEC), Saharsa",
  "Purnea Engineering College (PEC), Purnea",
  "Supaul Engineering College (SEC), Supaul",
  "Government Engineering College (GEC), Jamui",
  "Government Engineering College (GEC), Banka",
  "Government Engineering College (GEC), Vaishali",
  "Government Engineering College (GEC), Aurangabad",
  "Government Engineering College (GEC), Nawada",
  "Government Engineering College (GEC), Jehanabad",
  "Government Engineering College (GEC), Arwal",
  "Government Engineering College (GEC), Kaimur",
  "Government Engineering College (GEC), Bhojpur",
  "Government Engineering College (GEC), Buxar",
  "Government Engineering College (GEC), Munger",
  "Government Engineering College (GEC), Lakhisarai",
  "Government Engineering College (GEC), Khagaria",
  "Government Engineering College (GEC), Sheikhpura",
  "Government Engineering College (GEC), Samastipur",
  "Government Engineering College (GEC), Madhubani",
  "Government Engineering College (GEC), Gopalganj",
  "Government Engineering College (GEC), Siwan",
  "Shree Phanishwar Nath Renu Engineering College (SPNREC), Araria",
  "Government Engineering College (GEC), Kishanganj",
  "Government Engineering College (GEC), Sheohar",
  "Government Engineering College (GEC), West Champaran"
];

export default governmentEngineeringColleges
